version: 2

macrosGeneric:
  - &dockerhubCredentials
    username: $DOCKERHUB_USER
    password: $DOCKERHUB_PASSWORD

jobs:
  publish:
      docker:
        - image: asappinc/python-38-ci
          auth: *dockerhubCredentials
      steps:
        - checkout
        - run: python3.8 setup.py sdist bdist_wheel
        - run: twine upload --repository-url $PYPI_URL dist/*

workflows:
  version: 2
  build:
    jobs:
      - publish:
          context: asapp-build-standard
          requires:
            - test
          filters:
            branches:
              only: master
