# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dummydf": "00_core.ipynb",
         "pd.DataFrame.repetitions": "00_core.ipynb",
         "pd.DataFrame.repetition_counts": "00_core.ipynb",
         "pd.DataFrame.single_events": "00_core.ipynb",
         "pd.DataFrame.crosstab": "00_core.ipynb",
         "pd.DataFrame.len": "00_core.ipynb",
         "pd.Series.len": "00_core.ipynb",
         "l": "00_core.ipynb",
         "minmax": "00_core.ipynb",
         "pd.DataFrame.page": "00_core.ipynb",
         "pd.Series.page": "00_core.ipynb",
         "pd.DataFrame.renamec": "00_core.ipynb",
         "pd.Series.notin": "00_core.ipynb",
         "pd.Series.mapk": "00_core.ipynb",
         "pd.DataFrame.title": "00_core.ipynb",
         "Walker": "00_core.ipynb",
         "Less": "00_core.ipynb",
         "pd.DataFrame.less": "00_core.ipynb",
         "pd.DataFrame.to_percent": "00_core.ipynb",
         "pd.Series.less": "00_core.ipynb",
         "pd.DataFrame.c2back": "00_core.ipynb",
         "pd.DataFrame.c2front": "00_core.ipynb",
         "pd.DataFrame.reorderc": "00_core.ipynb",
         "replace_parentheses": "01_case.ipynb",
         "snake2words": "01_case.ipynb",
         "replace_acronyms": "01_case.ipynb",
         "acronyms": "01_case.ipynb",
         "pd.DataFrame.rename2words": "01_case.ipynb",
         "PxLabeler": "01_case.ipynb",
         "px_labeler": "01_case.ipynb",
         "Express": "01_case.ipynb",
         "px": "01_case.ipynb"}

modules = ["core.py",
           "case.py"]

doc_url = "https://ababino.github.io/pdpatch/"

git_url = "https://github.com/ababino/pdpatch/tree/main/"

def custom_doc_links(name): return None
