# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pd.DataFrame.repetitions": "00_core.ipynb",
         "pd.DataFrame.repetition_counts": "00_core.ipynb",
         "pd.DataFrame.single_events": "00_core.ipynb",
         "pd.DataFrame.crosstab": "00_core.ipynb",
         "pd.DataFrame.len": "00_core.ipynb",
         "pd.Series.len": "00_core.ipynb",
         "l": "00_core.ipynb",
         "minmax": "00_core.ipynb",
         "pd.DataFrame.page": "00_core.ipynb",
         "pd.Series.page": "00_core.ipynb",
         "pd.DataFrame.renamec": "00_core.ipynb",
         "pd.Series.notin": "00_core.ipynb",
         "pd.Series.mapk": "00_core.ipynb",
         "dummydf": "00_core.ipynb",
         "pd.DataFrame.title": "00_core.ipynb",
         "Walker": "00_core.ipynb",
         "Less": "00_core.ipynb",
         "pd.DataFrame.less": "00_core.ipynb",
         "pd.DataFrame.to_percent": "00_core.ipynb",
         "pd.Series.less": "00_core.ipynb",
         "pd.DataFrame.c2back": "00_core.ipynb",
         "pd.DataFrame.c2front": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pages.github.ASAPP.dev./ababino/pdpatch/"

git_url = "https://github.ASAPP.dev/ababino/pdpatch/tree/main/"

def custom_doc_links(name): return None
